server:
    servlet:
        context-path: /${spring.application.name}
spring:
    application:
        name: spring_cloud_server
    cloud:
        config:
            server:
                bootstrap: true
                git:
                    force-pull: true
                    password: <password>
                    uri: <uri>
                    username: <username>
                native:
                    search-locations: file:///C:/Users/taxie/Desktop/clases/Infraestructure_npe
    profiles:
        active: git,native
    security:
        user:
            name: <name>
            password: <password>
encrypt:
    key: <key>